config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :tags do
    # Nested route for related posts of a specific tag
    member do
      get 'posts', to: 'tags#posts', as: 'posts'
    end
  end

  resources :topics do
    get 'search', on: :collection
    resources :posts do
      post "read_unread", on: :member
      resources :comments do
        resources :comment_ratings, only: [:create, :update]
      end
      resources :ratings, only: [:create]
    end
  end

  resources :posts, only: [:index]

  # get 'toggle_theme', to: 'application#toggle_theme'

  # get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'topics#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title,presence: true ,uniqueness: true
  validates :genre,presence: true
  has_many :posts,dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]
  before_action :redirect_to_topic_path, only: [:edit]

  # GET /topics or /topics.json
  def index
    @pagy,@topics = pagy(Topic.all,items:5)

  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        # CreateTopicJob.perform_later(current_user)
        flash[:success] = 'Topic was successfully created.'
        format.html { redirect_to topics_path }
        format.json { render :index, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
        flash[:danger] = 'Topic creation failed.'
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        flash[:update] = 'Topic was successfully updated.'
        format.html { redirect_to topics_path }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
        flash[:danger] = 'Topic update failed.'
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      flash[:danger] = 'Topic was successfully destroyed.'
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  def search
    search = "%#{params[:search]}%"
    @topics = Topic.where("title LIKE ?", search)
  end

  def sample
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title, :genre)
    end
  def redirect_to_topic_path
    render plain: "Hello World"
  end
end

app/helpers/topics_helper.rb
module TopicsHelper

  def check_topic(title)
    if title[0] == "N"
      "Correct"
    else
      "Incorrect"
    end
  end
end

app/views/topics/_form.html.erb
<%= form_with(model: topic,local:true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field w-50 h-50 ms-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field w-50 h-50 ms-3">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: 'form-control' %>
  </div>
<br>
  <div class="actions ms-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/_search_topic.html.erb
<%= form_tag(search_topics_path, method: :get, class: 'form-inline') do %>
  <div class="input-group w-25">
    <%= text_field_tag :search, params[:search], class: 'form-control w-25', placeholder: 'Search by name' %>
    <div class="input-group-append ms-3">
      <%= submit_tag 'Search', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= topic.genre %></td>
<!--    <td><%#= check_topic(topic.title) %></td>-->
    <td><%= link_to 'Show', topic, class:"btn btn-info" %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic), class: "btn btn-success" %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
    <td><%= link_to 'Posts_list', topic_posts_path(topic), class: "btn btn-info" %></td>
  </tr>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>
<br>


<%= render "topics/search_topic" %>

<div align="end" class="me-5">
<%= link_to 'New Topic', new_topic_path, class:"btn btn-outline-info" %>
</div>

<h1>Topics</h1>
<%#= @topics.count %>
<div class="topic">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Result</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
  <%= render "topics/topic" %>
  </tbody>
</table>
</div>
<br>
<div class="container d-flex justify-content-center">
<%== pagy_nav(@pagy)%>
</div>

app/views/topics/new.html.erb
<div class="topic w-50 h-50 ms-3">
<h1>New Topic</h1>
</div>

<%= render 'form', topic: @topic %>
<br>
<%= link_to 'Back', topics_path, class:"btn btn-info ms-3" %>

app/views/topics/search.html.erb
<h1>Results</h1>
<div class="topic">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th colspan="4"></th>
    </tr>
    </thead>

    <tbody>
    <%= render "topics/topic" %>
    </tbody>
  </table>
</div>
<br>
<div class="container d-flex justify-content-center">
</div>

<%= link_to "back To Topics", root_path %>
<script>
  $(document).ready(function(){
    history.pushState(null, null, "<%= search_topics_path(@topic) %>");
  })
</script>

app/views/topics/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->
<div class="container d-flex justify-content-center">
<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>
</div>
<div class="container d-flex justify-content-center">
<p>
  <strong>Genre:</strong>
  <%= @topic.genre %>
</p>
</div>
<div class="container d-flex justify-content-center">
<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Posts', topic_posts_path(@topic) %> |
<%= link_to 'Back', topics_path %>
</div>