config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :tags do
    # Nested route for related posts of a specific tag
    member do
      get 'posts', to: 'tags#posts', as: 'posts'
    end
  end

  resources :topics do
    get 'search', on: :collection
    resources :posts do
      post "read_unread", on: :member
      resources :comments do
        resources :comment_ratings, only: [:create, :update]
      end
      resources :ratings, only: [:create]
    end
  end

  resources :posts, only: [:index]

  # get 'toggle_theme', to: 'application#toggle_theme'

  # get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'topics#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggables,dependent: :destroy
  has_many :posts,through: :taggables
  validates :name,presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    # @topic = Topic.find(params[:topic_id])
    @tags = Tag.all
    # redirect_to topic_post_url
  end

  def posts
    @tag = Tag.find(params[:id])
    @posts = @tag.posts
  end

  # GET /tags/1 or /tags/1.json
  def show
    @tag = Tag.find(params[:id])
    @posts = @tag.posts
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        flash[:success] = 'Tag was successfully created.'
        format.html { redirect_to tag_url(@tag) }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
        flash[:danger] = 'Tag creation failed.'
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        flash[:update] = 'Tag was successfully updated.'
        format.html { redirect_to tag_url(@tag) }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
        flash[:danger]= 'Tag update failed.'
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      flash[:danger] = 'Tag was successfully destroyed.'
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="container d-flex justify-content-center">Tags</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag ,class:"btn btn-primary"%></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) ,class:"btn btn-info"%></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %> |
<%= link_to 'Back to topics',root_path  %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<h1>Related Posts for <%= @tag.name %></h1>
<br>
<% @posts.each do |post| %>
  <h2>Posts:<%= post.description %></h2>
  <p>Topic_id:<%= post.topic_id %></p>
  <hr>
<% end %>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>