config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :tags do
    # Nested route for related posts of a specific tag
    member do
      get 'posts', to: 'tags#posts', as: 'posts'
    end
  end

  resources :topics do
    get 'search', on: :collection
    resources :posts do
      post "read_unread", on: :member
      resources :comments do
        resources :comment_ratings, only: [:create, :update]
      end
      resources :ratings, only: [:create]
    end
  end

  resources :posts, only: [:index]

  # get 'toggle_theme', to: 'application#toggle_theme'

  # get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'topics#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic

  has_one_attached :image

  has_many :comments,dependent: :destroy
  has_many :ratings,dependent: :destroy

  has_many :taggables,dependent: :destroy
  has_many :tags,through: :taggables

  belongs_to :user

  has_and_belongs_to_many :users, join_table: "posts_users_read_status", dependent: :destroy

  scope :filtered_by_date_range, ->(from_date, to_date) {
    @from_date = from_date
    @to_date = to_date
    where(created_at: from_date.beginning_of_day..to_date.end_of_day)
  }

  def update_rating_average
    new_average = ratings.average(:value).to_f.round(2)
    update_attribute(:rating_average, new_average)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_topic
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts =  (if @topic.present?
                      (@topic.posts.all.includes([:comments, :ratings]))
                      if params[:from_date].present? && params[:to_date].present?
                        @from_date = Date.parse(params[:from_date])
                        @to_date = Date.parse(params[:to_date])
                      else
                        # If no parameters provided, set default date range
                        @from_date = 1.day.ago.to_date
                        @to_date = Date.current
                      end

                      @filtered_posts = @topic.posts.filtered_by_date_range(@from_date, @to_date)
              else
                Post.all.includes(:topic)
               end)
  end
  # GET /posts/1 or /posts/1.json
  def show
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.find(params[:id])
    @tag = @post.tags
    @rating = Rating.new
    @rating_counts = @post.ratings.group(:value).count
  end

  # GET /posts/new
  def new
    @post = @topic.posts.build
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /posts/1/edit
  def edit
    authorize! :update, @post
  end

  # POST /posts or /posts.json
  def create
    @post = @topic.posts.build(post_params.except(:tags))
    create_or_delete_posts_tag(@post, params[:post][:tags])
    @post.user = current_user

    respond_to do |format|
      if @post.save
        @rating_counts = @post.ratings.group(:value).count
        flash[:success] = 'Post was successfully created.'
        format.html { redirect_to topic_post_path(@topic, @post) }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js { render "posts/errors" }
        flash[:danger] = 'Post creation failed.'
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    create_or_delete_posts_tag(@post, params[:post][:tags])
    @post.user = current_user

    respond_to do |format|
      if @post.update(post_params.except(:tags))
        flash[:success] = 'Post was successfully updated.'
        format.html { redirect_to topic_post_path(@topic) }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        flash[:danger] = 'Post was not  updated.'
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize! :destroy, @post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to topic_posts_path(@topic) }
      format.json { head :no_content }
      flash[:danger] = 'Post was successfully destroyed.'
    end
  end

  def read_unread
    @post = Post.find(params[:id])
    @post.users << current_user
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def create_or_delete_posts_tag(post, tags)
        post.taggables.destroy_all
        tags = tags.to_s.strip.split(',')
        tags.each do |tag|
          post.tags << Tag.find_or_create_by(name: tag.strip) unless tag.blank?
        end
    end

    def get_topic
      @topic = Topic.find(params[:topic_id]) if params[:topic_id].present?
    end
    def set_post
      @post = @topic.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :topic_id, :tags, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: [@topic, post], local: true, class:"new_form") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group d-flex justify-content-center">
    <%#= form.label :title %>
    <%= form.text_field :title,class:"form-control w-25", placeholder:"Add Title to the post" %>
  </div>
  <br>

  <div class="field form-group d-flex justify-content-center">
    <%#= form.label :description %>
    <%= form.text_field :description,class:"form-control w-25", placeholder:"Add Description to the post" %>
  </div>
  <br>
  <div class="field form-group d-flex justify-content-center">
    <%#= form.label :tags %>
    <%= form.text_field :tags, value: @post.tags.map(&:name).join(","),class:"form-control w-25", placeholder:"Add Tags to the posts" %>
  </div>

  <br>
  <div class="field form-group d-flex justify-content-center">
    <%= form.file_field :image,class:"form-control w-25", placeholder:"Add Images to the posts"%>
  </div>
  <br><br>

  <div class="actions field form-group d-flex justify-content-center">
    <%= form.submit "Submit", id: "post-submit", class:"btn btn-outline-success" %>
  </div>
  <br>
<% end %>

app/views/posts/_post_show.html.erb
<div class="post-details">
<!--  <p class="text-primary" id="notice"><%#= notice %></p>-->
  <!-- Post content -->
  <div>
    <strong>Post Title:</strong> <%= @post.title %>
  </div>
  <div>
    <strong>Description:</strong> <%= @post.description %>
  </div>
  <div>
    <strong>Topic:</strong> <%= @post.topic_id %>
  </div>

  <!-- Image -->
  <% if @post.image.attached? %>
    <%= image_tag @post.image, style: "width:300px;height:200px" %>
  <% else %>
    <p>No image available for this post.</p>
  <% end %>

  <!-- Tags -->
  <div>
    <strong>Tags:</strong>
    <% @post.tags.each do |tag| %>
      <%= link_to tag, class: "btn btn-info" do %>
        <span class="tags"><%= tag.name.capitalize %></span>
      <% end %>
    <% end %>
  </div>

  <h3>Rating Counts:</h3>
  <% (1..5).each do |value| %>
    <div><%= value %> star: <%= @rating_counts[value] || 0 %></div>
  <% end %>
  <br>

  <!-- Ratings -->
  <h2>Ratings:</h2>
  <%= form_for [@topic, @post, Rating.new] do |f| %>
    <% (1..5).each do |value| %>
      <%= "#{value} stars" %>
      <%= f.radio_button :value, value, onchange: 'this.form.submit();' %><br>
    <% end %>
  <% end %>

  <!-- Comments -->
  <h2>Comments:</h2>
  <% @post.comments&.each do |comment| %>
    <div class="comment-show">
      <p><%= link_to comment.content, topic_post_comment_path(@topic, @post, comment) %></p>
      <%= form_for [@topic, @post, comment, comment.comment_ratings.find_by(user_id: current_user.id) || CommentRating.new] do |f| %>
        <% (1..5).each do |value| %>
          <%= "#{value} " %>
          <%= f.radio_button :value, value %>
        <% end %>
        <%= f.submit 'Update Ratings', class: 'btn btn-info' %>
      <% end %>
      <%= link_to 'Delete', topic_post_comment_path(@topic, @post, comment),
                    method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
    </div>
    <hr>
  <% end %>

  <!-- Comment form -->
  <%= form_for([@topic, @post, Comment.new], local: true, id: 'comment-form') do |form| %>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content, rows: 4 %>
    </div>
    <div class="actions">
      <%= form.submit 'Save Comment', id: 'submit-button' %>
    </div>
  <% end %>

  <%= link_to 'Edit', edit_topic_post_path(@topic,@post) %> |
  <%= link_to 'Back', topic_posts_path(@topic) %>

  <script>
      // Read/unread status
      $(document).ready(function () {
          let token = $('meta[name="csrf-token"]').attr('content');
          if (!<%= @post.user_ids.include?(current_user.id) %>) {
              $.ajax({
                  url: '<%= read_unread_topic_post_path(@topic, @post) %>',
                  type: 'POST',
                  dataType: 'script',
                  headers: { 'X-CSRF-Token': token },
                  data: {
                      topic_id: <%= @topic.id %>,
                      id: <%= @post.id %>,
                  },
                  success: function (data) {
                      alert("Post has been read.");
                  },
                  error: function () {
                      alert("Error.");
                  }
              });
          }
      });

      // Color change
      $(document).ready(function () {
          let colorChange = $(".color-change");
          let count = 0;
          $("#changes").click(function () {
              const colorProperties = count % 2 === 0
                  ? { color: "black", backgroundColor: "lightgrey" }
                  : { color: "white", backgroundColor: "black" };
              colorChange.css(colorProperties);
              count++;
          });
      });
  </script>
</div>

app/views/posts/create.js.erb
alert("Post created Successfully");
setTimeout(function(){
    container.html(
      "<%= j render 'posts/post_show'%>"
    );
//    history.pushState(null, null, "<%#= topic_post_path(@topic, @post)%>");
    loadingSpinner.hide(); // Hide loading spinner after content is loaded
}, 500);

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', edit_topic_post_path(@topic, @post) %> |
<%= link_to 'Back', topic_posts_path(@topic) %>

app/views/posts/errors.js.erb
setTimeout(function(){
    formContainer.prepend(
        '<div id="error-explanation">'+
        "<%= @post.errors.full_messages %>"+
        '</div>'
    )
    setTimeout(function(){
        $("#error-explanation").remove();
    },500);
},1000)

app/views/posts/index.html.erb
<div id="post-container">
<!--  <p id="notice"><%#= notice %></p>-->
  <%= link_to 'Back to Topic', [@topic], class:"container d-flex justify-content-end" if @topic.present? %>
  <% if @posts.length > 0 %>

    <h1>Posts</h1>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Topic</th>
        <th>Average rating</th>
        <th>Comment count</th>
        <th>Post status</th>
        <th colspan="3">Action</th>
      </tr>
      </thead>

      <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title%></td>
          <td><%= post.description %></td>
          <td><%= post.topic.title %></td>
          <td><% if post.rating_average > 0 %>
               <%= post.rating_average %>
            <% else %>
              <p>No ratings available</p>
            <% end %>
          </td>
          <td><% if post.comments_count.present?  && post.comments_count > 0 %>
              <%= post.comments_count %>
            <% else %>
              <p>No comments available</p>
            <% end %>
          </td>
          <td>
            <% if post.user_ids.include?(current_user.id) %>
              <p>Read</p>
            <% else %>
              <p>Unread</p>
            <% end %>
          </td>
          <% if @topic.present? %>
            <td><%= link_to 'Show Post', topic_post_path(@topic,post),class: "btn btn-info" %></td>
            <td><%= link_to 'Edit post', edit_topic_post_path(@topic, post),class: "btn btn-success" %></td>
            <td><%= button_to 'Destroy post', [@topic, post], method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
          <% else %>
            <td><%= link_to 'Show Post', topic_post_path(post.topic, post),class: "btn btn-info" %></td>
            <td><%= link_to 'Edit post', edit_topic_post_path(post.topic, post),class: "btn btn-success" %></td>
            <td><%= button_to 'Destroy post', [post.topic, post], method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <br>
  <% else %>
    <p>No Posts available, you can also create the posts and view this page.</p>
  <% end %>

<% if @topic.present? %>
  <div id="form-container">
  </div>
  <div id="loading-spinner">
  </div>

  <button id="form-btn">New Post</button>
  <button id="cancel-btn">Cancel</button>
    <% end %>

<% if @topic.present? %>
  <br><br>
  <h1>Filtered Posts for <%= @topic.title %></h1>
  <%= form_tag(topic_posts_path(@topic), method: :get, id: "date-filter-form") do %>
    <label for="from_date">From Date:</label>
    <%= text_field_tag "from_date", nil, class: "datepicker" %>

    <label for="to_date">To Date:</label>
    <%= text_field_tag "to_date", nil, class: "datepicker" %>

    <%= submit_tag "Show Details" %>
  <% end %>
  <br>
  <ul>
    <% @filtered_posts.each do |post| %>
      <li><%= post.title %></li>
    <% end %>
  </ul>
  <% end %>

</div>

<% if @topic.present? %>
<script>
    let container = $("#post-container");
    let formContainer = $("#form-container");
    let formBtn = $("#form-btn");
    let cancelBtn = $("#cancel-btn");
    // let loadingSpinner = $(".loading-spinner"); // Make sure this class matches your HTML
    // let form = null;

    // formContainer.hide(); // Hide form container initially
    cancelBtn.hide();
    $(document).ready(function(){
        formBtn.click(function(){
            $.ajax({
                url: '<%= new_topic_post_path(@topic) %>',
                type: 'GET',
                dataType: 'script',
                success: function(data){
                    formBtn.hide();
                    cancelBtn.show();
                    // form_set(); // Corrected function call
                }
            });
        });

        cancelBtn.click(function(){
            formBtn.show();
            formContainer.empty();
            cancelBtn.hide();
        });
    });
</script>

<script>
    $(document).ready(function () {
        $(".datepicker").datepicker();
    });
</script>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>


<%= link_to 'Back', topic_posts_path(@topic),id:"back-hide" %>

app/views/posts/new.js.erb
formContainer.html(
    "<%= j render 'posts/form', post: @post %>"
)

$(".new_form").attr("data-remote","true");

app/views/posts/show.html.erb
<%= render 'posts/post_show', locals:{ post: @post} %>

<!--<%#= link_to 'Edit', edit_topic_post_path(@topic,@post) %> |-->
<%#= link_to 'Back', topic_posts_path(@topic) %>