config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :tags do
    # Nested route for related posts of a specific tag
    member do
      get 'posts', to: 'tags#posts', as: 'posts'
    end
  end

  resources :topics do
    get 'search', on: :collection
    resources :posts do
      post "read_unread", on: :member
      resources :comments do
        resources :comment_ratings, only: [:create, :update]
      end
      resources :ratings, only: [:create]
    end
  end

  resources :posts, only: [:index]

  # get 'toggle_theme', to: 'application#toggle_theme'

  # get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'topics#index'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand">Welcome to my project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a> <%= link_to 'Topics',root_path, class: "navbar-brand" %></a>
        </li>
        <li class="nav-item">
          <a><%= link_to 'Posts', posts_path, class: "navbar-brand" %></a>
        </li>
        <li class="nav-item">
          <a><%= link_to 'Tags', tags_path, class: "navbar-brand" %></a>
        </li>
      </ul>
      <div class="container w-100 d-flex justify-content-end">
        <a class="navbar-brand" href="#"></a>
        <% if user_signed_in? %>
          <%= link_to 'edit profile', edit_user_registration_path, class: 'btn btn-outline-info', remote: true, data: { 'bs-toggle' => "modal", "bs-target" => "#staticBackdrop" } %> ||
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-warning" %>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path, class: "navbar-brand" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Edit Profile</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
<!--      <div class="modal-footer">-->
<!--        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>-->
<!--        <button type="button" class="btn btn-primary">Understood</button>-->
<!--      </div>-->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>
  <%= render 'layouts/header' %>

  <% if flash[:success].present? %>
    <p class="alert alert-success text-center auto-dismiss" role="alert"><%= flash[:success] %></p>
  <% elsif flash[:danger].present? %>
    <p class="alert alert-danger text-center auto-dismiss" role="alert"><%= flash[:danger] %></p>
  <% elsif flash[:update].present? %>
    <p class="alert alert-info text-center auto-dismiss" role="alert"><%= flash[:update] %></p>
  <% end %>


  <%= yield %>
  </body>
</html>